[project]
name = "query-list"
authors = ["Anonymous Astronomer"]
description = "A decentralized registry for astronomical observations"
telemetry = false
requirements = []
[contracts.celestial-query-list]
path = "contracts/celestial-query-list.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
